# mkdocs.yml
site_name: calculator-learn
site_url: https://hananxr.github.io/calculator/

site_description: >- # é¡¹ç›®æè¿°
  Welcome to Han's knowledge store. Please note: This is an example of creating a project based on mkdocs, not a real project


# ä»£ç ä»“åº“ä¿¡æ¯
repo_name: HananxR # ä»“åº“åç§°
repo_url: https://github.com/HananxR/calculator.git # ä»“åº“åœ°å€

# ç‰ˆæƒä¿¡æ¯
copyright: Copyright &copy; 2025 ~ now | ğŸš€ HananxR



theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - home-page: index.md
  - install.md
  - tutorials.md
  - How-To-Guides: how-to-guides.md
  - reference.md
  - explanation.md